// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB6B73vrufL1RWmsjyZPQv1WqzdHhF_oQ',
    appId: '1:950897101349:web:d2eedd7e690a8f8fab4dcc',
    messagingSenderId: '950897101349',
    projectId: 'kigali-inventory',
    authDomain: 'kigali-inventory.firebaseapp.com',
    storageBucket: 'kigali-inventory.firebasestorage.app',
    measurementId: 'G-45EW8XK07N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNXxBAKdsse__1GVNXJFyrGBLp_IrZckA',
    appId: '1:950897101349:android:4bebf4ff7999cec6ab4dcc',
    messagingSenderId: '950897101349',
    projectId: 'kigali-inventory',
    storageBucket: 'kigali-inventory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoIAMaKqdULTHXKM0UsH3nsYxtmhuc3D8',
    appId: '1:950897101349:ios:2a1832e2f659d604ab4dcc',
    messagingSenderId: '950897101349',
    projectId: 'kigali-inventory',
    storageBucket: 'kigali-inventory.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoIAMaKqdULTHXKM0UsH3nsYxtmhuc3D8',
    appId: '1:950897101349:ios:2a1832e2f659d604ab4dcc',
    messagingSenderId: '950897101349',
    projectId: 'kigali-inventory',
    storageBucket: 'kigali-inventory.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityServices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB6B73vrufL1RWmsjyZPQv1WqzdHhF_oQ',
    appId: '1:950897101349:web:2716b2a5763c6746ab4dcc',
    messagingSenderId: '950897101349',
    projectId: 'kigali-inventory',
    authDomain: 'kigali-inventory.firebaseapp.com',
    storageBucket: 'kigali-inventory.firebasestorage.app',
    measurementId: 'G-YEFVC6QRY2',
  );
}
